//constants

export const ADD_USER_TO_STORE = "STORE.ADDUSER";
export const ADD_STUDENT_TO_STORE = "STORE.ADDSTUDENT";
export const ADD_HOBBY_TO_STORE = "STORE.ADDHOBBY";
export const FETCH_USER_HOBBIES = 'FETCH_HOBBIES';
export const ADD_PRODUCT_TO_STORE = "STORE.ADDPRODUCT";
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_ITEM_TO_STORE = 'CART.ADDITEM'